version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
